# Generated by Django 4.1.2 on 2022-10-28 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="capabilities",
            field=models.ManyToManyField(blank=True, to="character.capability"),
        ),
        migrations.AlterField(
            model_name="character",
            name="weapons",
            field=models.ManyToManyField(blank=True, to="character.weapon"),
        ),
        migrations.AlterField(
            model_name="path",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="character.profile",
            ),
        ),
        migrations.AlterField(
            model_name="path",
            name="race",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paths",
                to="character.race",
            ),
        ),
    ]
