# Generated by Django 4.1.2 on 2022-10-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0003_alter_character_equipment_alter_character_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="mana_max",
        ),
        migrations.RemoveField(
            model_name="character",
            name="mana_remaining",
        ),
        migrations.AddField(
            model_name="character",
            name="mana_consumed",
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
