# Generated by Django 4.1.2 on 2022-10-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0005_profile_notes_alter_character_mana_consumed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="path",
            name="category",
            field=models.CharField(
                choices=[
                    ("profile", "Profile"),
                    ("race", "Race"),
                    ("prestige", "Prestige"),
                    ("creature", "Creature"),
                ],
                max_length=20,
            ),
        ),
    ]
