# Generated by Django 4.1.2 on 2022-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0007_alter_capability_limited_alter_capability_spell"),
    ]

    operations = [
        migrations.AddField(
            model_name="capability",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="path",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="race",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="racialcapability",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
