# Generated by Django 4.1.2 on 2022-10-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0008_capability_url_path_url_profile_url_race_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="racialcapability",
            name="url",
        ),
    ]
