# Generated by Django 4.1.2 on 2022-10-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0010_racialcapability_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="racialcapability",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="racialcapability",
            constraint=models.UniqueConstraint(
                models.F("name"),
                models.F("race"),
                name="unique_name_race",
            ),
        ),
    ]
