# Generated by Django 4.1.2 on 2022-10-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0014_remove_character_mana_consumed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="recovery_points_remaining",
            field=models.PositiveSmallIntegerField(
                default=5, verbose_name="points de récupération restants"
            ),
        ),
    ]
