# Generated by Django 4.1.2 on 2022-10-30 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0018_character_damage_reduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="category",
            field=models.CharField(default="NON", max_length=3),
        ),
    ]
