# Generated by Django 4.1.2 on 2022-10-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0021_alter_character_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="level",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="niveau"),
        ),
    ]
