# Generated by Django 4.1.2 on 2022-10-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0022_alter_character_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="armor",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="armure"),
        ),
        migrations.AlterField(
            model_name="character",
            name="defense_misc",
            field=models.SmallIntegerField(default=0, verbose_name="divers défense"),
        ),
        migrations.AlterField(
            model_name="character",
            name="shield",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="bouclier"),
        ),
    ]
