# Generated by Django 4.1.2 on 2022-11-02 20:00

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0027_character_initiative_misc"),
    ]

    operations = [
        migrations.CreateModel(
            name="HarmfulState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="nom"),
                ),
                ("url", models.URLField(blank=True, verbose_name="url")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True,
                        verbose_name="modified",
                    ),
                ),
                ("description", models.TextField()),
                ("icon_url", models.URLField()),
            ],
            options={
                "verbose_name": "État préjudiciable",
                "verbose_name_plural": "États préjudiciables",
            },
        ),
    ]
