# Generated by Django 4.1.2 on 2022-11-02 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0028_harmfulstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="states",
            field=models.ManyToManyField(
                related_name="characters",
                to="character.harmfulstate",
            ),
        ),
    ]
