# Generated by Django 4.1.2 on 2022-11-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0029_character_states"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="states",
            field=models.ManyToManyField(
                blank=True,
                related_name="characters",
                to="character.harmfulstate",
            ),
        ),
    ]
