# Generated by Django 4.1.2 on 2022-11-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0030_alter_character_states"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="harmfulstate",
            options={
                "ordering": ["name"],
                "verbose_name": "État préjudiciable",
                "verbose_name_plural": "États préjudiciables",
            },
        ),
    ]
