# Generated by Django 4.1.2 on 2022-11-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0031_alter_harmfulstate_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="weapon",
            name="url",
            field=models.URLField(blank=True, verbose_name="url"),
        ),
    ]
