# Generated by Django 4.1.2 on 2022-11-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0033_party"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ["name"]},
        ),
    ]
