# Generated by Django 4.1.2 on 2022-11-02 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0034_alter_party_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="capability",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Capacité",
                "verbose_name_plural": "Capacités",
            },
        ),
        migrations.AlterModelOptions(
            name="harmfulstate",
            options={
                "get_latest_by": "modified",
                "ordering": ["name"],
                "verbose_name": "État préjudiciable",
                "verbose_name_plural": "États préjudiciables",
            },
        ),
        migrations.AlterModelOptions(
            name="party",
            options={
                "get_latest_by": "modified",
                "ordering": ["name"],
                "verbose_name": "Groupe",
                "verbose_name_plural": "Groupes",
            },
        ),
        migrations.AlterModelOptions(
            name="path",
            options={
                "get_latest_by": "modified",
                "ordering": ["name"],
                "verbose_name": "Voie",
                "verbose_name_plural": "Voies",
            },
        ),
        migrations.AlterModelOptions(
            name="profile",
            options={
                "get_latest_by": "modified",
                "ordering": ["name"],
                "verbose_name": "Profil",
                "verbose_name_plural": "Profils",
            },
        ),
        migrations.AlterModelOptions(
            name="race",
            options={
                "get_latest_by": "modified",
                "ordering": ["name"],
                "verbose_name": "Race",
                "verbose_name_plural": "Races",
            },
        ),
        migrations.AlterModelOptions(
            name="racialcapability",
            options={
                "get_latest_by": "modified",
                "verbose_name": "Capacité raciale",
                "verbose_name_plural": "Capacités raciales",
            },
        ),
        migrations.AlterModelOptions(
            name="weapon",
            options={
                "get_latest_by": "modified",
                "ordering": ["name"],
                "verbose_name": "Arme",
                "verbose_name_plural": "Armes",
            },
        ),
    ]
