# Generated by Django 4.1.2 on 2022-11-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "character",
            "0035_alter_capability_options_alter_harmfulstate_options_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Party",
        ),
    ]
