# Generated by Django 4.1.2 on 2022-11-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0036_delete_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="private",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Empêche toute invitation dans un groupe.",
                verbose_name="privé",
            ),
        ),
    ]
