# Generated by Django 4.1.4 on 2022-12-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0039_alter_character_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="gm_notes",
            field=models.TextField(blank=True, verbose_name="notes MJ"),
        ),
    ]
