# Generated by Django 4.1.7 on 2023-03-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0040_character_gm_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nom")),
                (
                    "health_max",
                    models.PositiveIntegerField(verbose_name="points de vie maximum"),
                ),
                (
                    "health_remaining",
                    models.PositiveIntegerField(verbose_name="points de vie restants"),
                ),
                (
                    "modifier_strength",
                    models.IntegerField(verbose_name="modificateur force"),
                ),
                (
                    "modifier_dexterity",
                    models.IntegerField(verbose_name="modificateur dextérité"),
                ),
                (
                    "modifier_constitution",
                    models.IntegerField(verbose_name="modificateur constitution"),
                ),
                (
                    "modifier_intelligence",
                    models.IntegerField(verbose_name="modificateur intelligence"),
                ),
                (
                    "modifier_wisdom",
                    models.IntegerField(verbose_name="modificateur sagesse"),
                ),
                (
                    "modifier_charisma",
                    models.IntegerField(verbose_name="modificateur charisme"),
                ),
                ("damage", models.PositiveIntegerField(verbose_name="dégâts")),
                ("initiative", models.PositiveIntegerField(verbose_name="initiative")),
                ("defense", models.PositiveIntegerField(verbose_name="défense")),
                ("attack", models.PositiveIntegerField(verbose_name="attaque")),
                (
                    "recovery",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="récupération",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to="character.character",
                    ),
                ),
            ],
        ),
    ]
