# Generated by Django 4.1.7 on 2023-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0041_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="damage",
            field=models.CharField(max_length=20, verbose_name="dégâts"),
        ),
    ]
