# Generated by Django 4.2.2 on 2023-06-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("character", "0042_alter_pet_damage"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="paths",
            field=models.ManyToManyField(
                blank=True,
                to="character.path",
                verbose_name="voies",
            ),
        ),
    ]
