# Generated by Django 4.2.9 on 2024-02-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("character", "0043_character_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="bonus_charisma",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="bonus charisme",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="bonus_constitution",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="bonus constitution",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="bonus_dexterity",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="bonus dextérité",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="bonus_intelligence",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="bonus intelligence",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="bonus_strength",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="bonus force",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="bonus_wisdom",
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name="bonus sagesse",
            ),
        ),
    ]
