services:
  django:
    build: .
    image: crocmagnon/charasheet
    env_file:
      - envs/docker-local-envs.env
    volumes:
      - ./src:/app/src
      - ./db:/app/db
    ports:
      - "8000:8000"
