version: "2.4"

services:
  django:
    build: .
    image: crocmagnon/charasheet
    command: /app/src/manage.py runserver 0.0.0.0:8000
    env_file:
      - envs/docker-local-envs.env
    volumes:
      - src:/app/src
      - db:/app/db
    ports:
      - "8000:8000"
