name: Test

on:
  workflow_call:
  pull_request:
    branches: [ "master" ]

jobs:
  tests:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Firefox
        run: sudo snap remove firefox && sudo add-apt-repository ppa:mozillateam/ppa && sudo apt install --target-release 'o=LP-PPA-mozillateam' firefox
      - uses: browser-actions/setup-geckodriver@latest
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Install dependencies
        run: |
          pip install pip-tools
          pip-sync requirements.txt requirements-dev.txt
      - name: Test
        run: pytest --cov=. --cov-branch --cov-report term-missing:skip-covered
        working-directory: ./src/
