name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * TUE'

permissions:
  contents: read

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: pip
      - name: Update dependencies
        run: |
          pip install pip-tools invoke
          invoke update-dependencies --no-sync
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        id: create-pull-request
        with:
          token: ${{ secrets.PERSONAL_TOKEN_PR }}
          commit-message: Update dependencies
          base: master
          branch: update-dependencies
          title: Update dependencies
          delete-branch: true
      - name: Enable auto merge
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN_PR }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
